[workspace]
members = [
    "linalg",
    "core",
    "hir",
    "tensorflow",
    "onnx",
    "kaldi",
    "cli",
    "examples/tensorflow-mobilenet-v2",
    "examples/jupyter-keras-tract",
    "harness/core-proptest-pulse",
    "harness/lstm-proptest-onnx-vs-tf",
    "harness/onnx-test-suite",
    "harness/tf-inceptionv3",
    "harness/tf-mobilenet-v2",
    "harness/tf-moz-deepspeech",
]

[profile.release]
lto = true

[profile.bench]
debug = true
