[package]
name = "core-proptest-pulse"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
tract-hir = { path = "../../hir" }

[dev-dependencies]
proptest = "0.9"
env_logger = "0.7"
