[package]
name = "tract"
version = "0.5.8-pre"
authors = [ "Romain Liautaud <romain.liautaud@snips.ai>", "Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ansi_term = "0.12.0"
atty = "0.2"
box_drawing = "0.1"
clap = "2.31"
env_logger = "0.6"
error-chain = "0.12"
itertools = "0.8"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
ndarray_0_12 = { version = "0.12", package = "ndarray" }
ndarray-npy = { version = "0.4", features = [ "compressed_npz" ] }
pbr = "1.0"
py_literal = "0.2"
rand = "0.7"
tract-core = { path = "../core" }
tract-kaldi = { optional = true, path = "../kaldi" }
tract-onnx = { optional = true, path = "../onnx" }
tract-tensorflow = { optional = true, path = "../tensorflow" }
winapi = "0.3"

[features]
default = ["kaldi", "onnx", "tf"]
kaldi = [ "tract-kaldi" ]
onnx = [ "tract-onnx" ]
tf = [ "tract-tensorflow" ]
conform = [ "tract-tensorflow/conform"  ]
