[package]
name = "tract-core"
version = "0.5.8-pre"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bit-set="0.5"
derive-new = "0.5"
downcast-rs = "1.0"
error-chain = "0.12"
half = "1.3"
itertools = "0.8"
log = "0.4"
maplit = "1.0"
ndarray = { version = "0.12" }
num-integer = "0.1"
num-traits = "0.2"
objekt = "0.1.1"
serde = { "version" = "1.0", optional = true }
serde_derive = { "version" = "1.0", optional = true }
smallvec = "0.6"
tract-linalg = { path = "../linalg" }
unsafe_unwrap = "0.1.0"
env_logger = "0.7"

[features]
default = [ ]
serialize = ["serde", "serde_derive", "smallvec/serde", "half/serde" ]

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[[bench]]
name = "conv_direct_vs_im2col"
harness = false

[[bench]]
name = "im2col_inception"
harness = false
