[package]
name = "deepspeech"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
log = "0.4"
tract-tensorflow = { path = "../../tensorflow" }

[dev-dependencies]
env_logger = "0.7"
