[package]
name = "tract-onnx"
version = "0.6.4-pre"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks", "ONNX" ]
categories = [ "science" ]
autobenches = false
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
bytes = "0.5"
derive-new = "0.5"
educe = "0.4"
error-chain = "0.12"
log = "0.4"
memmap = "0.7"
num-integer = "0.1"
prost = "0.6"
smallvec = "1"
tract-hir = { path = "../hir" }

[build-dependencies]
prost-build = "0.6"
