[package]
name = "example-tensorflow-mobilenet-v2"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"

[dependencies]
image = "*"
tract-tensorflow = { path = "../../tensorflow" }
