name: Native Linux

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  linux:
    strategy:
      matrix:
        rust: [ 1.39.0, stable ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Native script
      env:
        RUST_VERSION: ${{matrix.rust}}
      run: .travis/native.sh
